# Makefile automatically generated by ghdl
# Version: GHDL 3.0.0-dev (2.0.0.r394.g4afeced94) [Dunoon edition] - mcode code generator
# Command used to generate this makefile:
# C:\msys64\mingw32\bin\ghdl.exe gen-makefile one_hot_tb

GHDL=C:\msys64\mingw32\bin\ghdl.exe
GHDLFLAGS=
GHDLRUNFLAGS=

# Default target : elaborate
all : elab

# Elaborate target.  Almost useless
elab : force
	$(GHDL) -c $(GHDLFLAGS) -e one_hot_tb

# Run target
run : force
	$(GHDL) -c $(GHDLFLAGS) -r one_hot_tb $(GHDLRUNFLAGS)

# Targets to analyze libraries
init: force
	# C:\msys64\mingw32\lib/ghdl\ieee\v93\../../src/ieee/v93/std_logic_1164.vhdl
	# C:\msys64\mingw32\lib/ghdl\ieee\v93\../../src/ieee/v93/std_logic_1164-body.vhdl
	# C:\msys64\mingw32\lib/ghdl\ieee\v93\../../src/ieee/v93/numeric_std.vhdl
	# C:\msys64\mingw32\lib/ghdl\ieee\v93\../../src/ieee/v93/numeric_std-body.vhdl
	$(GHDL) -a $(GHDLFLAGS) util.vhd
	$(GHDL) -a $(GHDLFLAGS) one_hot_tb.vhd
	$(GHDL) -a $(GHDLFLAGS) cod.vhd
	$(GHDL) -a $(GHDLFLAGS) decod.vhd

force:
